
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "webserviceImpl", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebserviceImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendMail", targetNamespace = "http://service/", className = "service.SendMail")
    @ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://service/", className = "service.SendMailResponse")
    @Action(input = "http://service/webserviceImpl/sendMailRequest", output = "http://service/webserviceImpl/sendMailResponse")
    public void sendMail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateEmailAddress", targetNamespace = "http://service/", className = "service.ValidateEmailAddress")
    @ResponseWrapper(localName = "validateEmailAddressResponse", targetNamespace = "http://service/", className = "service.ValidateEmailAddressResponse")
    @Action(input = "http://service/webserviceImpl/validateEmailAddressRequest", output = "http://service/webserviceImpl/validateEmailAddressResponse")
    public boolean validateEmailAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendEmailBatch", targetNamespace = "http://service/", className = "service.SendEmailBatch")
    @ResponseWrapper(localName = "sendEmailBatchResponse", targetNamespace = "http://service/", className = "service.SendEmailBatchResponse")
    @Action(input = "http://service/webserviceImpl/sendEmailBatchRequest", output = "http://service/webserviceImpl/sendEmailBatchResponse")
    public void sendEmailBatch(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
